# Generated by Django 4.2.1 on 2023-05-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPIapp', '0002_alter_category_options_book_price_book_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='javadha', max_length=150),
        ),
    ]
